# Generated by Django 5.0.7 on 2024-07-21 19:24

import json
from django.db import migrations


def seed_psalm_verse(apps, _):
    Psalm = apps.get_model("psalter", "Psalm")

    with open("data/psalter.json") as f:
        data = json.load(f)

    for psalm_object in data:
        psalm = Psalm(
            number=psalm_object["number"],
            title=psalm_object["latin_title"],
        )
        psalm.save()
        for verse_object in psalm_object["verses"]:
            psalm.verse_set.get_or_create(
                number=verse_object["number"],
                first_half=verse_object["first_half"],
                second_half=verse_object["second_half"],
                psalm=psalm,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("psalter", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_psalm_verse)]
