# Generated by Django 5.0.7 on 2024-08-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('html', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('alt_name', models.CharField(blank=True, max_length=256, null=True)),
                ('service', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=16)),
                ('season', models.CharField(blank=True, choices=[('Advent', 'Advent'), ('Christmas', 'Christmas'), ('Epiphany', 'Epiphany'), ('Lent', 'Lent'), ('Easter', 'Easter'), ('Pentecost', 'Pentecost')], max_length=16, null=True)),
                ('color', models.CharField(blank=True, choices=[('violet', 'Violet'), ('white', 'White'), ('green', 'Green'), ('red', 'Red'), ('rose', 'Rose'), ('blue', 'Blue')], max_length=16, null=True)),
                ('lessons', models.ManyToManyField(to='lectionary.lesson')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='lectionary__name_3faa50_idx')],
            },
        ),
    ]
