# Generated by Django 5.0.7 on 2024-07-20 21:24

import json
from django.db import migrations


def seed_data(apps, _):
    Day = apps.get_model("lectionary", "Day")

    with open("data/lectionary.json") as f:
        data = json.load(f)

    for day_name, val in data.items():
        if day_name == "Christmas Day" or day_name == "Easter Day":
            for service_name, years in val.items():
                for year_name, lessons in years.items():
                    day_object = Day(
                        name=day_name, year=year_name[-1], service=service_name
                    )
                    day_object.save()
                    for lesson_list in lessons.values():
                        day_object.lesson_set.get_or_create(
                            scripture=" or ".join(lesson_list)
                        )
        else:
            for year_name, lessons in val.items():
                day_object = Day(name=day_name, year=year_name[-1])
                day_object.save()
                for lesson_list in lessons.values():
                    day_object.lesson_set.get_or_create(
                        scripture=" or ".join(lesson_list)
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
