# Generated by Django 5.0.7 on 2024-08-08 14:26

import json
from django.db import migrations


def day_lesson_data(apps, _):
    Day = apps.get_model("lectionary", "Day")
    Lesson = apps.get_model("lectionary", "Lesson")
    DayLesson = apps.get_model("lectionary", "DayLesson")

    with open("data/lectionary.json") as f:
        data = json.load(f)

    for day_name, val in data.items():
        if day_name.startswith("Christmas") or day_name.startswith("Easter"):
            for service_name, years in val.items():
                for year_name, lessons in years.items():
                    day = Day(name=day_name, year=year_name, service=service_name)
                    day.save()
                    for lesson_list in lessons.values():
                        reference = " or ".join(lesson_list)
                        lesson, created = Lesson.objects.get_or_create(
                            reference=reference
                        )
                        if created:
                            lesson.save()
                        day_lesson = DayLesson(day=day, lesson=lesson)
                        day_lesson.save()
        else:
            for year_name, lessons in val.items():
                day = Day(name=day_name, year=year_name)
                day.save()
                for lesson_list in lessons.values():
                    reference = " or ".join(lesson_list)
                    lesson, created = Lesson.objects.get_or_create(reference=reference)
                    if created:
                        lesson.save()
                    day_lesson = DayLesson(day=day, lesson=lesson)
                    day_lesson.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(day_lesson_data),
    ]
