# Generated by Django 5.0.7 on 2024-07-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0002_seed_day_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="esv_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="esv_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
