# Generated by Django 5.0.7 on 2024-08-08 14:34

import json
from django.db import migrations


def season_color_data(apps, _):
    Day = apps.get_model("lectionary", "Day")

    with open("data/seasons.json") as f:
        data = json.load(f)

    for key, val in data.items():
        days = Day.objects.filter(name=key)
        for day in days:
            day.season = val["season"]
            day.color = val["color"]
            day.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0002_day_lesson_data"),
    ]

    operations = [
        migrations.RunPython(season_color_data),
    ]
