# Generated by Django 5.0.7 on 2024-08-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectionary', '0003_season_color_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectionary.day')),
            ],
        ),
    ]
