# Generated by Django 5.0.7 on 2024-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectionary', '0004_lesson_psalm_html_lesson_psalm_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='color',
            field=models.CharField(blank=True, choices=[('VI', 'Violet'), ('WH', 'White'), ('GR', 'Green'), ('RE', 'Red'), ('RO', 'Rose'), ('BL', 'Blue')], max_length=2, null=True),
        ),
    ]
