# Generated by Django 5.0.7 on 2024-08-12 21:09

import json
from django.db import migrations


def collect_data(apps, _):
    Day = apps.get_model("lectionary", "Day")
    Collect = apps.get_model("lectionary", "Collect")
    DayCollect = apps.get_model("lectionary", "DayCollect")

    with open("data/collects.json") as f:
        data = json.load(f)

    for name, collects in data.items():
        for text in collects:
            collect = Collect(text=text)
            collect.save()
            for day in Day.objects.filter(name=name):
                day_collect = DayCollect(day=day, collect=collect)
                day_collect.save()


class Migration(migrations.Migration):
    dependencies = [
        ("lectionary", "0004_collect_daycollect_day_collects"),
    ]

    operations = [
        migrations.RunPython(collect_data),
    ]
