# Generated by Django 5.0.7 on 2024-08-06 19:47

import json
from django.db import migrations

def seed_season_color(apps, _):
    Day = apps.get_model("lectionary", "Day")

    with open("data/seasons.json") as f:
        data = json.load(f)

    for key, val in data.items():
        days = Day.objects.filter(name=key)
        for day in days:
            day.season = val["Season"]
            day.color = val["Color"]
            day.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lectionary', '0005_day_color'),
    ]

    operations = [
        migrations.RunPython(seed_season_color),
    ]
