name: Format and lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install djlint
      - name: Run Ruff formatter
        run: ruff format .
      - name: Run Ruff linter
        run: ruff check --output-format=github .
      - name: Run djLint formatter
        run: djlint --profile django --reformat .
      - name: Run djLint linter
        run: djlint --profile django --lint .
